# Generated by Django 6.0.4 on 2026-04-29 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='role_id',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='role',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='store_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
