# Generated by Django 6.0.4 on 2026-05-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0003_remove_shopuser_role_id_shopuser_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={},
        ),
    ]
