# Generated by Django 6.0.4 on 2026-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('secure', '0004_alter_shopuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='secure_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='secure_users', to='auth.permission'),
        ),
    ]
