# Generated by Django 6.0.4 on 2026-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/avatar-placeholder.png', upload_to='avatar/'),
        ),
    ]
