# Generated by Django 6.0.4 on 2026-05-14 16:12

import apps.secure.helpers
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0007_shopuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='store_credit',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.secure.helpers.generate_api_key, max_length=64, unique=True)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
