# Generated by Django 6.0.4 on 2026-05-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product-image/coat_img.webp', null=True, upload_to='product-image/'),
        ),
    ]
