# Generated by Django 6.0.4 on 2026-05-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0003_shopuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='raw_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
