# Generated by Django 6.0.4 on 2026-05-14 17:33

import apps.vulnerable.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0004_shopuser_raw_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='store_credit',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.vulnerable.models.generate_api_key, max_length=64, unique=True)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='vulnerable.shopuser')),
            ],
        ),
    ]
