# Generated by Django 6.0.4 on 2026-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0005_remove_shopuser_store_credit_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10.0', max_digits=6),
            preserve_default=False,
        ),
    ]
